version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb # создаётся временно, потом init.sql создаст базы
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build:
      context: ./auth-service
    container_name: auth_service
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/auth_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3001:3000"

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/user_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3002:3000"

  post-service:
    build:
      context: ./post-service
    container_name: post_service
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/post_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3003:3000"

volumes:
  pgdata:
