events {}

http {
   upstream auth_service {
    server auth-service:3000;
  }

  upstream user_service {
    server user-service:3000;
  }

  upstream post_service {
    server post-service:3000;
  }

  server {
    listen 80;
    server_name localhost;
    
    # Auth service
    location /auth/ {
      proxy_pass http://auth_service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # User service
    location /users/ {
      proxy_pass http://user_service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
    }

    # Post service
    location /posts/ {
      proxy_pass http://post_service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
