events {}

http {
  upstream gateway {
    server gateway:3000;
  }

  server {
    listen 80;
    server_name localhost;
    # location / {

    #  return 301 http://localhost:4001;

    #   # proxy_pass http://localhost:3000;
    #   # proxy_set_header Host $host;
    #   # proxy_set_header X-Real-IP $remote_addr;
    # }

    location / {
      proxy_pass http://gateway;
    }
  }
}
